baseURL: "https://thesustainableloop.com"
title: "The Sustainable Loop"
theme: "dimension"
enableRobotsTXT: true
disableKinds:
    - RSS

Params:
    logo: "/images/thesustainableloop.png"
    supporterLogos:
    - iconurl: /images/impacthub.png
    - iconurl: /images/berlin.png
    - iconurl: /images/esf.png
    social:
    - type: linkedin
      url: "https://www.linkedin.com/in/mirjam-born-b75a88170"
    - type: instagram
      url: "https://www.instagram.com/the.sustainable.loop"

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
    de:
        languageName: Deutsch
        description: "Beratung & Forschung zu öko-fairer Kleidung"
        supporterTitle: "Unterstützt durch:"
    en:
        languageName: English
        description: "Consulting & Research for Eco-Fair Clothing"
        supporterTitle: "Supported by:"
