baseURL: "https://thesustainableloop.com"
title: "The Sustainable Loop"
theme: "dimension"
enableRobotsTXT: true
disableKinds:
    - RSS

Params:
    iconclass: "fa-gem"
    #logo: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Font_Awesome_5_regular_gem.svg"

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
    de:
        languageName: Deutsch
        description: "Beratung & Forschung zu öko-fairer Kleidung"
    en:
        languageName: English
        description: "Consulting & Research for Eco-Fair Clothing"
